const CONFIRMATION_AMOUNT: number = 6;
const CONFIRMATION_AMOUNT_IN_DEV_NETWORK: number = 1;
const DEV_CHAIN_ID: number = 31337;

export {
	CONFIRMATION_AMOUNT,
	CONFIRMATION_AMOUNT_IN_DEV_NETWORK,
	DEV_CHAIN_ID,
};
